### ISSUE TITLE
Issue with compiling Graph factorization using bjam.

### ISSUE THREAD

**Issue by jeetu-raj** [palash1992/GEM#10]
I compiled the graph factorization cpp files in c_src using bjam. For the compilation I made the following changes:

* rename Jamfile to Jamroot.jam
* comment run-test line in Jamfile - otherwise an error is raised
* compile with std=c++11

Post compilation two files were created - graphFac.o, graphFac_ext.so 

I was unable to use it with your python gem interface. I am not sure whether this is the right way to compile and set it up . Can you please describe the steps for setting up graph factorization? I am hoping to speed up the learning process by using the code. 

Aside issue : Hope implementation is very memory intense , How much memory did you need for running on YouTube graph in your experiment?

**Comment by palash1992** [comment]
To compile the graph factorization code, you need the command "bjam toolset=gcc cxxflags="-std=c++11"". I didn't need to rename the Jamfile but if renaming worked for you, it's fine. You can write one line in "graphFacLoad.py", "import graphFace_ext" and the above bjam command would verify if it can be imported from Python. Also, did you place the graphFac_ext.so in the c_ext folder where GEM is installed? Otherwise it will use the file already in the folder which was compiled on my PC.

Yes, the current implementation of HOPE is for small networks as scipy doesn't support GSVD as of now. For large networks, you can use MATLAB's gsvd implementation to get the embedding and GEM's functions to evaluate it. I am planning to implement a memory efficient version of HOPE in Python but it might take a bit of time.

**Comment by jeetu-raj** [comment]
I created a graphFacLoad.py which just had import graphFac_ext . I got the following error while compiling.
![image](https://user-images.githubusercontent.com/11074925/31325744-2b66ad2e-acde-11e7-926e-e02e04b0c6d9.png)

I commented the line in Jamfile again and was able to compile the code.  To test whether I am able to include graphFac_ext I simply tried to run "python graphFacLoad.py"

I got the following error on doing this , Can you please take a look into the issue.
**graphFac_ext.so: undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv**

Thanks

**Comment by palash1992** [comment]
Can you check to see if you are able to compile a sample program using boost and use it in Python (for e.g., hello world)? I believe your Boost is not configured properly and thus you are getting this error. You can checkout this link to see if it helps, https://stackoverflow.com/questions/1780003/import-error-on-boost-python-hello-program.  
Alternatively, if you cannot get Boost to work, you can avoid using Boost and pass the arguments as command line arguments to the C++ file (comment out the boost part and add main function) and use system call from Python to call the C++ executable.
