### ISSUE TITLE
Experiment Speed

### ISSUE THREAD

**Issue by can-keklik** [palash1992/GEM#36]
Hello,

What is expected run time for big datasets like YOUTUBE? Experimental setup described in the paper is very powerful, have you tried with average hardware?

Thanks.

**Comment by palash1992** [comment]
Hi,

For big data sets, it takes days to train a model. Yes, the experimental setup is indeed powerful as it takes a lot longer on smaller computers. Since most models have many hyperparameters to tune, a good computer is needed to find optimal configuration for a model.

If you have a smaller computer, I would recommend using GF and node2vec as they are the fastest among the models and give pretty good results.

Regards,
Palash Goyal
