### ISSUE TITLE
SDNE Test Error

### ISSUE THREAD

**Issue by GamalC** [palash1992/GEM#8]
I am trying to use SDNE but I am getting the following traceback:

> Traceback (most recent call last):
>   File "gem/embedding/sdne.py", line 260, in <module>
>     embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
>   File "gem/embedding/sdne.py", line 115, in learn_embedding
>     self._encoder = get_encoder(self._node_num, self._d, self._K, self._n_units, self._nu1, self._nu2, self._actfn)
>   File "GEM/gem/embedding/sdne_utils.py", line 16, in get_encoder
>     y[i+1] = Dense(n_units[i], activation=activation_fn, W_regularizer=Reg.l1_l2(l1=nu1, l2=nu2))(y[i])
> AttributeError: 'module' object has no attribute 'l1_l2'

It seems like some sort of Keras error. Any help/insight you can give will be appreciated.

Additionally, why did you re-implement SDNE when a reference implementation is available online? I tried using it and the embeddings I am getting from it are quite poor so I am wondering if you had a similar experience.

Thanks!

**Comment by palash1992** [comment]
You are getting the error because you are using a newer version of keras.
You can change "l1_l2" to "l1l2" and it will work for your version (will
give some other warnings for the future versions).

When I started writing the code there was no other implementation of sdne
available so I coded or myself.

On Sep 11, 2017 8:52 AM, "Gamal Crichton" <notifications@github.com> wrote:

I am trying to use SDNE but I am getting the following traceback:

Traceback (most recent call last):
File "gem/embedding/sdne.py", line 260, in
embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True,
no_python=True)
File "gem/embedding/sdne.py", line 115, in learn_embedding
self._encoder = get_encoder(self._node_num, self._d, self._K,
self._n_units, self._nu1, self._nu2, self._actfn)
File "GEM/gem/embedding/sdne_utils.py", line 16, in get_encoder
y[i+1] = Dense(n_units[i], activation=activation_fn,
W_regularizer=Reg.l1_l2(l1=nu1, l2=nu2))(y[i])
AttributeError: 'module' object has no attribute 'l1_l2'

It seems like some sort of Keras error. Any help/insight you can give will
be appreciated.

Additionally, why did you re-implement SDNE when a reference implementation
is available online? I tried using it and the embeddings I am getting from
it are quite poor so I am wondering if you had a similar experience.

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palash1992_GEM_issues_8&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=K3r5hqgNRwE3uMJxm-hxBXu9zAYbuZIXLKxkVp56vvw&s=i8V8keNARfBuQJokHBbsbGLJ1A4uoSQBlkoeF1INAeY&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABH2RfOhMQ8yvLricvDsLDPg7h5don6Zks5shVclgaJpZM4PTYOM&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=K3r5hqgNRwE3uMJxm-hxBXu9zAYbuZIXLKxkVp56vvw&s=lRWbgU62hMHQkdloJlmivNimRyVLr97nXCqQ4cbT9gk&e=>
.

**Comment by GamalC** [comment]
Thanks for your prompt reply! It is much appreciated. Thanks for the response about why you implemented it as well.

I did what you suggested and it fixed that error. It is now giving another. It is a shape error and I really can't see where it is getting the extra value from:

> Traceback (most recent call last):
>   File "gem/embedding/sdne.py", line 260, in <module>
>     embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
>   File "gem/embedding/sdne.py", line 182, in learn_embedding
>     OutData[:k,2*self._node_num] ], nb_epoch=1, batch_size=self._n_batch, shuffle=True, verbose=1) 
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 952, in fit
>     batch_size=batch_size)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 883, in _standardize_user_data
>     exception_prefix='model target')
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 98, in standardize_input_data
>     str(array.shape))
> Exception: Error when checking model target: expected merge_2 to have shape (None, 34) but got array with shape (150, 35)

**Comment by palash1992** [comment]
The problem is probably with the input graph or dimensions (maybe trying to
embed a graph with 34 nodes in more than 34 dimensions?). You will have to
take a closer look yourself as I/other people who used this never faced
this issue. Let me know when you figure it out.

**Comment by GamalC** [comment]
OK. Thanks for the reply.
It seems I was using an older version of Keras, not a newer one. Upgrading seems to have solved the issues. 
Sorry for the trouble.
