### ISSUE TITLE
error while running the example given in the readme

### ISSUE THREAD

**Issue by vinayakathavale** [palash1992/GEM#9]
Hello,
I tried to run the example given in the readme but get the following error:

> Could not import C++ module for Graph Factorization. Reverting to python implementation. Please recompile graphFac_ext from graphFac.cpp using bjam
Traceback (most recent call last):
  File "1.py", line 12, in <module>
    Y, t = em.learn_embedding(graph, edge_f=None, is_weighted=True, no_python=True)
  File "/home/vinayak/Research/Graph/GEM/gem/embedding/gf.py", line 80, in learn_embedding
    [f1, f2, f] = self._get_f_value(graph)
  File "/home/vinayak/Research/Graph/GEM/gem/embedding/gf.py", line 46, in _get_f_value
    for i, j, w in graph.edges_iter(data='weight', default=1):
AttributeError: 'DiGraph' object has no attribute 'edges_iter'

**Comment by palash1992** [comment]
Hi Vinayak,

Please update your networkx and the error should be fixed.

Regards,
Palash Goyal

**Comment by vinayakathavale** [comment]
I updated networkx to version 2.0 but still am facing the same error.

**Comment by palash1992** [comment]
As per the networkx documentation, they removed the edges_iter attribute in
their 2.0 release and replaced it with edges. I would suggest reverting
back the version to 1.11. If in other projects you are using v2.0 and
reverting would be an issue you can replace edges_iter with edges in your
version of my code.

On Sep 26, 2017 12:49 AM, "vinayak athavale" <notifications@github.com>
wrote:

I updated networkx to version 2.0 but still am facing the same error.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palash1992_GEM_issues_9-23issuecomment-2D332115511&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=4iefID-dGmFcs2INX6aCkV54YMU3w0P6cki3iv1URrM&s=b-vAfp7AGDg_bG41R7G3sTmoYKfR5lzwW8HEQJzFHrY&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABH2RUa9RoiXf5CkKg-5FVaYHD8p0Ew585ks5smKxxgaJpZM4Ph2AD&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=I_A-ZJGnHcHAuxuBmINQ-Q&m=4iefID-dGmFcs2INX6aCkV54YMU3w0P6cki3iv1URrM&s=eSHUqffg9X10Jp0h0q6Y6O0ixGYcOqH_BlzvOqwMptw&e=>
.

**Comment by guemues** [comment]
Same error continues for me on 1.11 as well.

**Comment by trbn** [comment]
I have this problem too. I have replaced edges_iter with edges but there is no changes in the error.

**Comment by wxnudt** [comment]
I have the same error with networkx 1.11
